project: 
  type: website
  resources:
    - CNAME
    - "content/resources/"
  render:
    - content/index.qmd
    - content/sb.qmd
    - content/fgb.qmd
    - content/gr.qmd
    - content/fk.qmd
    - content/oc.qmd
    - content/cb.qmd
    - content/mb.qmd
    - content/ch.qmd
    - content/ci.qmd
    - content/pm.qmd
    - content/as.qmd
    - content/hi.qmd
    - content/ne.qmd
    - content/np.qmd
    - content/nc.qmd

website: 
  page-navigation: true
  title: "NOAA quarto simple" 
  site-url: "https://ci-cmg.github.io/SoundscapesWebsiteDev/content/" 
  repo-url: "https://github.com/CI-CMG/SoundscapesWebsiteDev"
  repo-actions: [source, issue]
  favicon: images/image.png
  
  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; CC-1.0"
  
  sidebar:
    background: "#AABFC1"
    logo: images/image.png
    favicon: images/favicon.ico
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://sanctuaries.noaa.gov/
        text: "Office of National Marine Sanctuaries"

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - text: <b>General</b>
      - href: content/index.qmd
        text: Home
      - href: https://sanctuaries.noaa.gov/science/monitoring/sound/
        target: _blank
        text: ONMS Sound Project Page
      - href: https://www.pmel.noaa.gov/acoustics/noaanps-ocean-noise-reference-station-network
        target: _blank
        text: NOAA Noise Reference Station Network
      - href: https://sanctsound.ioos.us/sounds.html
        target: _blank
        text: Sanctuary Sound Library
      - text: <br>
      - text: <b>Eastern Region</b>
      - href: content/sb.qmd
        text: Stellwagen Bank
      - href: content/fgb.qmd
        text: Flower Garden Banks
      - href: content/gr.qmd
        text: Gray's Reef
      - href: content/fk.qmd
        text: Florida Keys
      - href: content/ne.qmd
        text: New England
      - text: <br>
      - text: <b>West Coast Region</b>
      - href: content/oc.qmd
        text: Olympic Coast
      - href: content/cb.qmd
        text: Greater Farallones and Cordell Bank 
      - href: content/mb.qmd
        text: Monterey Bay
      - href: content/ch.qmd
        text: Chumash Heritage
      - href: content/ci.qmd
        text: Channel Islands
      - href: content/nc.qmd
        text: Humboldt Coast
      - text: <br>
      - text: <b>Pacific Islands Region</b>
      - href: content/pm.qmd
        text: Papahānaumokuākea
      - href: content/as.qmd
        text: American Samoa
      - href: content/hi.qmd
        text: Hawaiian Islands Humpback Whale
      - text: <br>
      - text: <b>Alaska Region</b>
      - href: content/np.qmd
        text: Gulf of Alaska

format:
  html:
    theme:
      light: [cosmo, theme.scss] 
      dark: [cosmo, theme-dark.scss]
    grid: 
      body-width: "1200px"     
      sidebar-width: "250px" 
      margin-width: "250px" 
    code-copy: true
    code-overflow: wrap
    toc: true
    page-layout: full


filters:
  - include-files.lua
  - quarto
  
  